### ISSUE TITLE
about recipe . 

### ISSUE THREAD

**Issue by brendenlai** [openbmc/phosphor-net-ipmid#1]
hi all , 
     it works to build  netipmid binary with follow steps.
    1. ./bootstrap.sh
    2. ./configure ${CONFIGURE_FLAGS}
    3. make

     but failed  when i try to integrate this feature with bitbake via recipe .
     here is my recipe .

do_configure () {
	 cd ${S}
	./bootstrap.sh
	./configure ${CONFIGURE_FLAGS}	
}

do_compile() {
	
	make
	arm-openbmc-linux-gnueabi-strip ./netipmid
}

do_install () {
        install -m 0755 -d ${D}${bindir} 
        install -m 0644 ${S}/netipmid ${D}${bindir}

}
    it failed within do_configure task. attach log .  
    Is that possible to provide a recipe for  install this feature in image ?
[config.log](https://github.com/openbmc/phosphor-net-ipmid/files/2824369/config.log)

**Comment by amboar** [comment]
Hello @brendenlai,

There's already a recipe for it here:

https://github.com/openbmc/meta-phosphor/blob/master/recipes-phosphor/ipmi/phosphor-ipmi-net_git.bb

There shouldn't be any need to write your own. If something is wrong about the existing recipe we should fix it.

Cheers, Andrew
