### ISSUE TITLE
The SOL session will be disconnected after receiving a packet once.

### ISSUE THREAD

**Issue by allenyu800901** [openbmc/phosphor-net-ipmid#29]
When I input "sol activate usesolkeepalive", I reboot the OS. At this time, the SOL session can receive the postcode message, but there is only one data, and then the SOL will be disconnected immediately. Has anyone encountered this issue?
![23](https://github.com/user-attachments/assets/6c221d26-42f6-474c-8c27-2db38682b608)

**Comment by thangtran-ampere** [comment]
I got this issue, you can find out more information in this discussion https://discord.com/channels/775381525260664832/1107848576995954688/1299257372656799744

**Comment by allenyu800901** [comment]
@thangtran-ampere 
Thank you for your information,

For this issue, if I want to enable rmcp_ping, I should set the config.h file simultaneously so that it can be referenced, but the code change will be relatively large.

So I want to try turning off rmcp_ping first, If I want to disable rmcp_ping, in phosphor-net-ipmid
Is it enough to set the value to disabeld in /meson.options? Or are other additional settings required?

thanks for your reply.

**Comment by thangtran-ampere** [comment]
The rmcp-ping build option is enbaled by default, you can see here https://github.com/openbmc/openbmc/blob/master/meta-phosphor/recipes-phosphor/ipmi/phosphor-ipmi-net_git.bb#L36.

If you want to disable rmcp-ping build option, you have to remove this option in the package, please refer to this commit https://github.com/openbmc/openbmc/commit/29380ed6d328bfd45a3c4e389cdfcb97359052aa for more information.

I hope this solution work with you.

**Comment by allenyu800901** [comment]
@thangtran-ampere 
After modifying according to your suggestions, my sol session can operate normally. 
Thank you very much for sharing the information.
